// Visual regression — generated by qaia-playwright:visual-check against ExpenseFlow (US-004).
// Second domain for this skill: it had one reference suite (examples/medibook) and no proof it
// generates against anything else (#18).
//
// Tolerance: maxDiffPixelRatio 0.002 on every snapshot, the skill's stated default. 0.2 % of a
// screen's pixels absorbs anti-aliasing and font hinting between runs on one machine; a moved
// button, a wrong colour or a shifted layout each move far more than that. No snapshot here
// raises it — raising a tolerance to make a test pass is the failure mode the skill forbids.
//
// Determinism: every test resets the SUT and scopes the snapshot to a stable container rather
// than the viewport. The one genuinely dynamic value on this app — the date input, which a
// browser may default to today — is filled with a fixed date rather than masked, because a
// frozen value gives an exact 0-pixel diff where a mask only hides the region.
//
// Baselines are platform-specific (`*-win32.png` here). Regenerate them in the environment the
// CI runs, or the diff means nothing.
const { test, expect } = require('./fixtures');
const { LoginPage } = require('./pages/LoginPage');
const { ReportsPage } = require('./pages/ReportsPage');

const B = process.env.BASE_URL || 'http://localhost:4500'; // honore BASE_URL comme la config (B1)
const TOL = { maxDiffPixelRatio: 0.002 };
// Figee pour que les pixels soient stables, ET dans la fenetre des 90 jours -- ce qui
// n'etait vrai que jusqu'au 2026-10-24, puisque le SUT compare a son horloge. Demarrer la
// demo avec DEMO_NOW=2026-07-26 (voir README des tests) rend la paire deterministe.
const FIXED_DATE = '2026-07-25';

test.describe('ExpenseFlow visual (US-004)', () => {
  test.beforeEach(async ({ request }) => {
    await request.post(B + '/api/reset');
  });

  test('@QAIA-VIS-001 sign-in screen', async ({ page }) => {
    const login = new LoginPage(page);
    await login.goto();
    await expect(page.locator('#login-section')).toHaveScreenshot('login.png', TOL);
  });

  test('@QAIA-VIS-002 sign-in screen with a rejected credential', async ({ page }) => {
    // The error state is a screen in its own right: a regression that breaks the message's
    // colour or placement is invisible to the functional tests, which only assert its text.
    const login = new LoginPage(page);
    await login.goto();
    await login.signIn('employee@demo', 'wrong-password');
    await expect(login.error).toBeVisible();
    await expect(page.locator('#login-section')).toHaveScreenshot('login-error.png', TOL);
  });

  test('@QAIA-VIS-003 reports screen, empty state', async ({ page }) => {
    const login = new LoginPage(page);
    await login.goto();
    await login.signIn('employee@demo', 'demo1234');
    const reports = new ReportsPage(page);
    await expect(reports.mine).toContainText('No reports.');
    await expect(page.locator('#app-section')).toHaveScreenshot('reports-empty.png', TOL);
  });

  test('@QAIA-VIS-004 draft form with one line filled', async ({ page }) => {
    const login = new LoginPage(page);
    await login.goto();
    await login.signIn('employee@demo', 'demo1234');
    const reports = new ReportsPage(page);
    await reports.startDraft();
    await reports.fillLine(0, { category: 'travel', amount: 42.5, date: FIXED_DATE, receipt: true });
    await expect(page.locator('#draft-section')).toHaveScreenshot('draft-one-line.png', TOL);
  });

  test('@QAIA-VIS-005 my reports after a submission', async ({ page }) => {
    const login = new LoginPage(page);
    await login.goto();
    await login.signIn('employee@demo', 'demo1234');
    const reports = new ReportsPage(page);
    await reports.startDraft();
    await reports.fillLine(0, { category: 'travel', amount: 42.5, date: FIXED_DATE, receipt: true });
    await reports.submitReportBtn.click();
    await expect(reports.mine).toContainText('submitted');
    await expect(reports.mine).toHaveScreenshot('mine-submitted.png', TOL);
  });

  test('@QAIA-VIS-006 approver inbox', async ({ page, request }) => {
    // Seeded through the API rather than the UI: the screen under test is the inbox, and driving
    // the submission through the browser would make this snapshot depend on the draft form too.
    const t = await (await request.post(B + '/api/login', {
      data: { email: 'employee@demo', password: 'demo1234' },
    })).json();
    const created = await (await request.post(B + '/api/reports', {
      headers: { Authorization: 'Bearer ' + t.token },
    })).json();
    await request.put(B + '/api/reports/' + created.report.id, {
      headers: { Authorization: 'Bearer ' + t.token },
      data: { currency: 'EUR', lines: [{ category: 'travel', amount: 42.5, date: FIXED_DATE, receipt: true }] },
    });
    await request.post(B + '/api/reports/' + created.report.id + '/submit', {
      headers: { Authorization: 'Bearer ' + t.token },
    });

    const login = new LoginPage(page);
    await login.goto();
    await login.signIn('manager@demo', 'demo1234');
    const reports = new ReportsPage(page);
    await expect(reports.inbox).toContainText('submitted');
    await expect(reports.inbox).toHaveScreenshot('inbox-pending.png', TOL);
  });
});
